{{- if .Values.credentialAuthz.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: credential-authz
  namespace: {{ .Values.platformNamespace.name }}
  labels:
    {{- include "k8s-debug-agents.labels" . | nindent 4 }}
    app.kubernetes.io/component: credential-authz
{{- end -}}
